apiVersion: v1
kind: Service

metadata:
  name: snyk-demo-app-service

spec:
  selector:
    app: snyk-demo-app

  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

  type: ClusterIP